# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title     : Foundation Mathematics
# author    : "<a href='mailto:z.ma@mmu.ac.uk'>Dr Zhihua Ma</a>"
author    : "Dr Zhihua Ma"
copyright : "2023---2025"  # Copyright year to be placed in the footer
logo      : images/logo.svg
email     : "z.ma@mmu.ac.uk"

only_build_toc_files: true 


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: odebook.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/zhihuammu/ODE-book  # Online location of your book
  path_to_book: / # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # favicon               : images/logo/odefavicon.png  # A path to a favicon image
  home_page_in_navbar   : false
  use_multitoc_numbering: true     
  use_repository_button : false
  use_edit_page_button  : false
  use_issues_button     : false
  use_download_button   : false
  use_source_button     : false 
  comments:
    hypothesis          : false
  announcement          : ""
  
sphinx:
  config:
    # bibtex_reference_style: author_year    
    html_show_copyright: true
    language: en
    # latex_engine: 'xelatex'
    # latex_elements:
    #     preamble: |
    #       \newcommand{\N}{\mathbb{N}}
    #       \newcommand{\Z}{\mathbb{Z}}
    #       \newcommand{\R}{\mathbb{R}}
    #       \newcommand{\C}{\mathbb{C}}
    #       \newcommand{\D}{\mathrm{D}}
    #       \newcommand{\E}{\mathrm{E}}
    #       \newcommand{\S}{\mathrm{S}}
    #       \newcommand{\dy}{\mathrm{d}y}
    #       \newcommand{\dx}{\mathrm{d}x}
    #       \newcommand{\ds}{\mathrm{d}s}
    #       \newcommand{\dt}{\mathrm{d}t}
    #       \usepackage{physics}                                            
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "Z": "\\mathbb{Z}"
          "R": "\\mathbb{R}"
          "C": "\\mathbb{C}"
          "D": "\\mathrm{D}"
          "E": "\\mathrm{E}"
          "S": "\\mathrm{S}"          
          "dy": "\\mathrm{d}y"
          "dx": "\\mathrm{d}x"
          "ds": "\\mathrm{d}s"
          "dt": "\\mathrm{d}t"
          "i" : "\\mathbf{\\hat{i}}"
          "diff": ["\\frac{\\mathrm{d}^{#1}{#2}}{\\mathrm{d}{#3}^{#1}}",3,'']
          "pdiff": ["\\frac{\\partial^{#1}{#2}}{\\partial{#3}^{#1}}",3,'']
    hide_solutions: false
    html_theme: sphinx_book_theme
    # html_theme: sphinx_rtd_theme
    # html_theme: pydata_sphinx_theme
    # templates_path: ['_templates']  #This conflicts with sphinx_book_theme
    html_theme_options:    
      navigation_with_keys: True
      show_toc_level  : 3      
      footer_start  : sphinx-version
      footer_end    : theme-version    
      # extra_navbar  : "FOOBAR2" #not supported anymore
      # extra_footer  : "<div>Powered by <a href='https://jupyterbook.org'>Jupyter Book</a></div>"
      # primary_sidebar_end: 
      #   - sphinx-version
      #   - copyright
      #   - theme-version
      #   - last-updated
      # content_footer_items:
      #   - theme-version
      #   - last-updated
      #   - copyright
      #   - sphinx-version
      # navbar_start      : navbar-logo
      # navbar_center     : navbar-nav
      # navbar_end        : navbar-icon-links
      # navbar_persistent : search-button
      # navbar_align      : right
    # html_sidebars :
      # '**': 
        # - navbar-logo
        # - search-field        
        # - sbt-sidebar-nav
        # - indices        
      # secondary_sidebar_items:
        # - page-toc
        # - edit-this-page
    html_last_updated_fmt : "%A %d %B %Y %H:%M:%S"
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise    
    - sphinxcontrib.tikz
    - sphinx_togglebutton      
    - sphinx_inline_tabs    

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - html_admonition
    - fieldlist   
    - deflist    
  # myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: false  # Allow display math ($$) within an inline context    

  
